In [1]:
from datascience import *
import numpy as np
%matplotlib inline
import matplotlib.pyplot as plots
plots.style.use('fivethirtyeight')
import warnings
warnings.simplefilter(action="ignore", category=FutureWarning)

from urllib.request import urlopen 
import re
def read_url(url): 
    return re.sub('\\s+', ' ', urlopen(url).read().decode())

/Users/ayushthasale07/Sarg<3/Data8/.venv/lib/python3.9/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(

In [3]:
import math

math.sqrt(8)

In [5]:
math.sqrt(8)

2.8284271247461903

In [6]:
round(8 ** 0.5, 3)

2.828

In [8]:
# Tables
cones = Table.read_table("cones.csv")
cones

Flavor     | Color       | Price
strawberry | pink        | 3.55
chocolate  | light brown | 4.75
chocolate  | dark brown  | 5.25
strawberry | pink        | 5.25
chocolate  | dark brown  | 5.25
bubblegum  | pink        | 4.75

In [10]:
cones.show(2)

In [12]:
cones.select("Flavor")

Flavor
strawberry
chocolate
chocolate
strawberry
chocolate
bubblegum

In [13]:
cones.select('Flavor', 'Price')

Flavor     | Price
strawberry | 3.55
chocolate  | 4.75
chocolate  | 5.25
strawberry | 5.25
chocolate  | 5.25
bubblegum  | 4.75

In [14]:
cones.where("Flavor", "chocolate")

Flavor    | Color       | Price
chocolate | light brown | 4.75
chocolate | dark brown  | 5.25
chocolate | dark brown  | 5.25

In [15]:
cones.sort("Price")

Flavor     | Color       | Price
strawberry | pink        | 3.55
chocolate  | light brown | 4.75
bubblegum  | pink        | 4.75
chocolate  | dark brown  | 5.25
strawberry | pink        | 5.25
chocolate  | dark brown  | 5.25

In [17]:
nba = Table.read_table("nba_salaries.csv")
nba

rank | name             | position | team                   | salary   | season
1    | Shaquille O'Neal | C        | Los Angeles Lakers     | 17142000 | 2000
2    | Kevin Garnett    | PF       | Minnesota Timberwolves | 16806000 | 2000
3    | Alonzo Mourning  | C        | Miami Heat             | 15004000 | 2000
4    | Juwan Howard     | PF       | Washington Wizards     | 15000000 | 2000
5    | Scottie Pippen   | SF       | Portland Trail Blazers | 14795000 | 2000
6    | Karl Malone      | PF       | Utah Jazz              | 14000000 | 2000
7    | Larry Johnson    | F        | New York Knicks        | 11910000 | 2000
8    | Gary Payton      | PG       | Seattle SuperSonics    | 11020000 | 2000
9    | Rasheed Wallace  | PF       | Portland Trail Blazers | 10800000 | 2000
10   | Shawn Kemp       | C        | Cleveland Cavaliers    | 10780000 | 2000
... (9446 rows omitted)

In [20]:
nba_pg = nba.where("position", "PG")
nba_pg_2000 = nba_pg.where("season", 2000)

In [21]:
nba_pg_2000

rank | name             | position | team                   | salary   | season
8    | Gary Payton      | PG       | Seattle SuperSonics    | 11020000 | 2000
11   | Damon Stoudamire | PG       | Portland Trail Blazers | 10125000 | 2000
20   | Stephon Marbury  | PG       | New Jersey Nets        | 9000000  | 2000
24   | Nick Van Exel    | PG       | Denver Nuggets         | 8354000  | 2000
26   | Terrell Brandon  | PG       | Minnesota Timberwolves | 7400000  | 2000
34   | Jason Kidd       | PG       | Phoenix Suns           | 6858000  | 2000
35   | Kenny Anderson   | PG       | Boston Celtics         | 6680000  | 2000
39   | Steve Nash       | PG       | Dallas Mavericks       | 5500000  | 2000
55   | Charlie Ward     | PG       | New York Knicks        | 4540000  | 2000
61   | Darrel Armstrong | PG       | Orlando Magic          | 4125000  | 2000
... (12 rows omitted)