In [20]:
from datascience import *
import numpy as np
import matplotlib.pyplot as plt

%matplotlib inline

In [21]:
survey = Table.read_table("welcome_survey_sp22.csv")
survey.show(5)

In [22]:
survey.select("Year", "Hours of sleep").group("Year", collect=np.mean).take(1, 7, 8, 3)

Year   | Hours of sleep mean
First  | 7.19757
Second | 7.1778
Third  | 6.96696
Fourth | 6.92188

In [23]:
survey.select("Handedness", "Sleep position", "Hours of sleep").group(["Handedness", "Sleep position"], collect=np.mean).show()

In [24]:
survey.pivot("Handedness", "Sleep position")

Sleep position     | Both | Left-handed | Right-handed
On your back       | 2    | 15          | 299
On your left side  | 1    | 30          | 315
On your right side | 3    | 31          | 451
On your stomach    | 3    | 17          | 176

In [25]:
survey.pivot("Handedness", "Sleep position","Hours of sleep", collect=np.mean)

Sleep position     | Both    | Left-handed | Right-handed
On your back       | 5       | 7.06667     | 7.11538
On your left side  | 6       | 6.96667     | 7.11905
On your right side | 8.16667 | 7.04839     | 7.11863
On your stomach    | 8.33333 | 7.5         | 7.25284

In [26]:
sky = Table.read_table("skyscrapers.csv")
sky = sky.with_column("age", 2026 - sky.column("completed")).drop("completed")
sky.show(5)

In [30]:
sky_g = sky.select("name", "city", "material", "height", "age").group(["city", "material"], collect=max)
sky_g

city      | material        | name max                                | height max | age max
Atlanta   | concrete        | Westin Peachtree Plaza                  | 264.25     | 50
Atlanta   | mixed/composite | Two Alliance Center                     | 311.8      | 39
Atlanta   | steel           | State of Georgia Building               | 169.47     | 129
Austin    | concrete        | Windsor on the Lake                     | 208.15     | 42
Austin    | steel           | University of Texas Tower               | 93.6       | 89
Baltimore | concrete        | The John and Frances Angelos Law Center | 161.24     | 59
Baltimore | steel           | Mercy Medical Center Inpatient Tower    | 155.15     | 115
Boston    | concrete        | Harbor Towers II                        | 121.92     | 55
Boston    | mixed/composite | Ellison Building                        | 139        | 34
Boston    | steel           | Two International Place                 | 240.79     | 111
... (81 rows omitted)

In [37]:
sky_p = sky.pivot("material", "city", "height", np.max)
sky_p

city       | concrete | mixed/composite | steel
Atlanta    | 264.25   | 311.8           | 169.47
Austin     | 208.15   | 0               | 93.6
Baltimore  | 161.24   | 0               | 155.15
Boston     | 121.92   | 139             | 240.79
Charlotte  | 265.48   | 239.7           | 179.23
Chicago    | 423.22   | 306.94          | 442.14
Cincinnati | 125      | 202.69          | 175
Cleveland  | 125      | 288.65          | 215.8
Columbus   | 79.25    | 0               | 169.3
Dallas     | 176.48   | 280.72          | 270.06
... (25 rows omitted)

In [38]:
sky_p_withconc_steel_diff = sky_p.with_column("diffconst", abs(sky_p.column("steel") - sky_p.column("concrete")))

In [39]:
sky_p_withconc_steel_diff

city       | concrete | mixed/composite | steel  | diffconst
Atlanta    | 264.25   | 311.8           | 169.47 | 94.78
Austin     | 208.15   | 0               | 93.6   | 114.55
Baltimore  | 161.24   | 0               | 155.15 | 6.09001
Boston     | 121.92   | 139             | 240.79 | 118.87
Charlotte  | 265.48   | 239.7           | 179.23 | 86.25
Chicago    | 423.22   | 306.94          | 442.14 | 18.92
Cincinnati | 125      | 202.69          | 175    | 50
Cleveland  | 125      | 288.65          | 215.8  | 90.8
Columbus   | 79.25    | 0               | 169.3  | 90.05
Dallas     | 176.48   | 280.72          | 270.06 | 93.58
... (25 rows omitted)

In [47]:
def take_the_first_one(a):
    return a.item(0)

sky.sort("age", descending=True).pivot("material", "city", "name",take_the_first_one)

city       | concrete                         | mixed/composite                           | steel
Atlanta    | Westin Peachtree Plaza           | One Atlantic Center                       | FlatironCity
Austin     | One American Center              |                                           | University of Texas Tower
Baltimore  | Charles Towers North Apartments  |                                           | Emerson Tower
Boston     | Harbor Towers I                  | Ellison Building                          | Marriott's Custom House
Charlotte  | Bank of America Corporate Center | Hearst Tower                              | Midtown Plaza
Chicago    | The Powhatan                     | American Furniture Mart                   | The Rookery
Cincinnati | Kroger Building                  | Great American Tower at Queen City Square | PNC Tower
Cleveland  | National City Center             | 55 Public Square                          | Huntington Bank Building
Columbus   | Key Bank Building                |                                           | Leveque Tower
Dallas     | Reunion Tower                    | Bank of America Plaza                     | Three AT&T Plaza
... (25 rows omitted)